### ISSUE TITLE
Gurobi not working with Pyomo 6.8.0 as specified in requirements

### ISSUE THREAD

**Issue by ChriKo97** [FZJ-IEK3-VSA/FINE#66]
On solving the model with Pyomo 6.8.0 as required by fine I run into the type error `TypeError: addConstr() got an unexpected keyword argument 'sense'` in line 526 here : /site-packages/pyomo/solvers/plugins/solvers/gurobi_direct.py Using pyomo 6.9.1 fixes this issue. Is an update of requirements to use pyomo==6.9.1 possible?
