### PR TITLE
add support for python 3.13

### LINKED ISSUE #66: Gurobi not working with Pyomo 6.8.0 as specified in requirements
On solving the model with Pyomo 6.8.0 as required by fine I run into the type error `TypeError: addConstr() got an unexpected keyword argument 'sense'` in line 526 here : /site-packages/pyomo/solvers/plugins/solvers/gurobi_direct.py Using pyomo 6.9.1 fixes this issue. Is an update of requirements to use pyomo==6.9.1 possible?

### PR DESCRIPTION
**Pull request by maurerle**
This PR adds support for Python 3.13 and updates required dependencies to work with latest versions.

supersedes #67 
closes #66 

Generally, I like the approach to be open to new versions much more, and only provide minimum versions better, but the current approach is of course fine as well, if it keeps being maintained.

### CODE REVIEW

**Comment by maurerle** [comment]
@t-gross is there an option to add this, as this closes an issue we have with gurobipy?

**Comment by maurerle** [comment]
@JohannesBehrens could you please take a look? It has been 5 month now that FINE is not usable with python 3.13...

**Comment by phil-fzj** [comment]
hi @maurerle. Sorry for the delay and thank you for your PR!
I just tested this and there seem to be no issues in our pipeline.

Could you also change the version constraints in the 
- requirements_dev.yml
- requirements.yml

Then we can merge this!

**Comment by maurerle** [comment]
Finally :)
Thanks @phil-fzj  - i just updated this PR by rebasing and added your suggested change :)

**Comment by JohannesBehrens** [comment]
Thanks @maurerle for the code update.
We are currently working on migrating the full fine repository (including our test pipelines) to github. Once this is done I will merge your Request today.

**Comment by julian-belina** [comment]
@MaurerLe, thank you for your efforts to improve fine. Unfortunately, there are still some unresolved issues.

I have set up a pipeline to test Fine for versions 3.10, 3.11, 3.12 and 3.13, for installation via PyPi and Conda Forge. Therefore, I have forked your branch [here](https://github.com/julian-belina/FINE), @maurerle. So i can insepct Github actions more easily.

The results can be found here: https://github.com/FZJ-IEK3-VSA/FINE/actions/runs/17839572203/job/50796565110.


1. It seems that, when installing the dependencies from PyPI, our examples yield different results to the expected values for all Python versions. The .ipynb files appear to have some kind of built-in test. I have not yet figured out how these are implemented.
2. Fine with Python 3.13 is not installable from Conda Forge due to the pandas <=0.1.14 constraint.


The constraints cannot be officially relaxed until both issues have been resolved. @LarsHadidi  has already started working on this. I hope we can combine our efforts soon. Otherwise, @JohannesBehrens and @phil-fzj , we need to take a look at this.

**Comment by phil-fzj** [comment]
To 1) 
The test works as such that the notebooks outputs are checked against the stored values of cells tagged with _nbval-check-output_.
The issue is that the stored version of the notebook was probably run with numpy<2 while the pipeline runs with numpy>2. This results in slightly different formatted outputs:
e.g. examples/01_1node_Energy_System_Workflow/01_1node_Example.ipynb 
output for `data["Wind (onshore), operationRateMax"].sum()`:
Original notebook cell content: 
`"text/plain": [ "2300.4069071646272" ]`
Cell output with numpy>2:
`"text/plain": ["np.float64(2300.4069071646272)"]`

This causes the tests to fail despite the values actually being the same.
We could think about casting all the outputs to float explicitly, e.g.:
`float(data["Wind (onshore), operationRateMax"].sum())`
then the output is:
`"text/plain": [ "2300.4069071646272" ]`
regardless of the numpy version.
 
This way, tests should pass for both numpy 1&2

**Comment by maurerle** [comment]
@julian-belina
1. the issues you describe are unrelated to this PR.
2. Your pipeline now runs for different OS types but always with python3.10
3. I did not find a `pandas <=0.1.14` constraint - did you mean geopandas with `<=0.14.4` could be bumped to 1.x eventually?

**Comment by julian-belina** [comment]
@maurerle Sorry, there were some errors in my last post.

The correct pipeline can be found at this link: https://github.com/julian-belina/FINE/actions/runs/17863033778. This workflow differs from the standard pipeline, which is intended for testing new features rather than updating dependencies.

It would be great if you could reopen the pull request for this branch: https://github.com/FZJ-IEK3-VSA/FINE/tree/70_add_ci. This would allow me to run a different pipeline.

Secondly, I meant geopandas <=0.14.4 and not pandas <=0.14.4. While installing from PyPI works fine, it is not possible to create the environment from Conda Forge when using requirements-dev.yml.
This causes this pipeline to fail. 

@phil-fzj  It seems that @maurerle  has already implemented this. Once the other pipeline has passed, we can merge it.

**Comment by maurerle** [comment]
@julian-belina 
I added working yml versions to my branch (you can rebase, cherry-pick or merge this into your branch as needed).
Various dependencies were in need of a version bump (and some still are).

The output you saw in the pipeline is just a symptom. The root cause is that other packages - like psutil, xarray and numpy were in need of a relaxation of the version requirements.

In general, I would either have open dependency versions and regularly check that everything works in CI (as done in https://github.com/assume-framework/assume) or add a dependabot or whatever to get informed of new versions and incrementally test these.

**Review by julian-belina — APPROVED** [review]
It passes all relevant tests and allows the installation of Python 3.10–3.13.

**Comment by julian-belina** [comment]
@maurerle Thank you for your contribution.

Some adaptations to the tests were necessary to set the names of Pandas data frame indices. Interestingly, this only occurred when installing Pandas from Conda Forge. 

Unfortunately, due to a long backlog of maintenance tasks, we did not update the dependency requirements earlier. This will improve in future releases. However, we want to stick to constrained installation requirements so that fine can always be easily installed. Breaking changes in dependency releases occur quite often, and we cannot guarantee that we can immediately update to be compatible with them, but we try to keep up with the pace.

File: pyproject.toml [hunk 1]
```diff
@@ -34,22 +34,22 @@ dependencies = [
     "openpyxl<=3.1.5",
     "matplotlib<=3.9.2",
     "xlrd<=2.0.1",
-    "pyomo<=6.8.0",
-    "numpy<=1.26.4",
+    "pyomo<=6.9.4",
+    "numpy<=2.2.4",
     "pandas>=2,<=2.2.3",
-    "scipy<=1.14.1",
```
Comment (julian-belina) [inline pyproject.toml:40]: I didnt see that, but I will setup a test pipeline for older numpy versions and relax the constaints

Comment (phil-fzj) [reply pyproject.toml:40]: my bad, i already removed the comment you are replying to as i noticed that I was wrong.
everything should be fine.
